AWSTemplateFormatVersion: '2010-09-09'
Description: 'StackSet Layer 4: UI - App Runner Service'

Parameters:
  StackPrefix:
    Type: String
    Default: workshop
    Description: Prefix for all resources
  
  Environment:
    Type: String
    Default: workshop
    Description: Environment name
  
  MasterAccountId:
    Type: String
    Description: Master account ID for ECR cross-account access (passed from deployment script)

Resources:
  # ==========================================
  # IAM Role for App Runner Instance
  # ==========================================
  
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeAsync
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackPrefix}-*'
        - PolicyName: SSMParameterPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackPrefix}/*'

  # ==========================================
  # IAM Role for App Runner Access (ECR)
  # ==========================================
  
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Policies:
        - PolicyName: CrossAccountECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ECRTokenAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Sid: ECRImageAccess
                Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchCheckLayerAvailability
                  - ecr:DescribeImages
                Resource:
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${MasterAccountId}:repository/${StackPrefix}-ui-master'

  # ==========================================
  # App Runner Service
  # ==========================================
  
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub '${StackPrefix}-ui'
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Sub '${MasterAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${StackPrefix}-ui-master:latest'
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '3003'
            RuntimeEnvironmentVariables:
              - Name: NODE_ENV
                Value: production
              - Name: PORT
                Value: '3003'
              - Name: AWS_REGION
                Value: !Ref AWS::Region
              - Name: STACK_PREFIX
                Value: !Ref StackPrefix
              # Cognito Configuration
              - Name: COGNITO_USER_POOL_ID
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/user-pool-id}}'
              - Name: COGNITO_CLIENT_ID
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/client-id}}'
              - Name: COGNITO_REGION
                Value: !Ref AWS::Region
              - Name: COGNITO_DOMAIN
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/cognito-domain}}'
              # Coveo Configuration
              - Name: COVEO_ORG_ID
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/org-id}}'
              - Name: COVEO_SEARCH_API_KEY
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/search-api-key}}'
              - Name: COVEO_PLATFORM_URL
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/platform-url}}'
              - Name: COVEO_SEARCH_PIPELINE
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/search-pipeline}}'
              - Name: COVEO_SEARCH_HUB
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/search-hub}}'
              - Name: COVEO_ANSWER_CONFIG_ID
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/answer-config-id}}'
              - Name: COVEO_RESULTS_PER_PAGE
                Value: '20'
              # API Gateway URL
              - Name: API_GATEWAY_URL
                Value: !Sub '{{resolve:ssm:/${StackPrefix}/coveo/api-gateway-url}}'
      InstanceConfiguration:
        Cpu: '1024'
        Memory: '2048'
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      AutoScalingConfigurationArn: !GetAtt AppRunnerAutoScaling.AutoScalingConfigurationArn
      Tags:
        - Key: Name
          Value: !Sub '${StackPrefix}-ui'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # App Runner Auto Scaling
  # ==========================================
  
  AppRunnerAutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub '${StackPrefix}-ui-autoscaling'
      MaxConcurrency: 100
      MaxSize: 10
      MinSize: 1
      Tags:
        - Key: Name
          Value: !Sub '${StackPrefix}-ui-autoscaling'
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # SSM Parameter for App Runner URL
  # ==========================================
  
  AppRunnerUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${StackPrefix}/coveo/app-runner-url'
      Type: String
      Value: !GetAtt AppRunnerService.ServiceUrl
      Description: App Runner service URL

Outputs:
  ServiceUrl:
    Description: App Runner service URL
    Value: !GetAtt AppRunnerService.ServiceUrl
    Export:
      Name: !Sub '${StackPrefix}-AppRunnerUrl'
  
  ServiceArn:
    Description: App Runner service ARN
    Value: !GetAtt AppRunnerService.ServiceArn
    Export:
      Name: !Sub '${StackPrefix}-AppRunnerArn'
  
  ServiceId:
    Description: App Runner service ID
    Value: !GetAtt AppRunnerService.ServiceId
    Export:
      Name: !Sub '${StackPrefix}-AppRunnerId'
