AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Bedrock Agent with Coveo Passage Retrieval action group'

Parameters:
  StackPrefix:
    Type: String
    Description: Prefix for all resource names
    Default: coveo-workshop
  
  Environment:
    Type: String
    Description: Environment name
    Default: dev
    AllowedValues:
      - dev
      - workshop
      - prod
  
  PassageToolFunctionArn:
    Type: String
    Description: ARN of the Lambda function for passage retrieval tool
  
  BedrockFoundationModel:
    Type: String
    Description: Bedrock foundation model ID for the agent
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    AllowedValues:
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-instant-v1

Resources:
  # IAM role for Bedrock Agent
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StackPrefix}-bedrock-agent-role'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/solution-engineer-boundary'
      Description: Execution role for Bedrock Agent
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: BedrockModelInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockFoundationModel}'
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Ref PassageToolFunctionArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref StackPrefix

  # Bedrock Agent
  CoveoAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Sub '${StackPrefix}-coveo-agent'
      Description: 'Bedrock Agent with Coveo Passage Retrieval for Finance & Travel Knowledge Hub'
      AgentResourceRoleArn: !GetAtt BedrockAgentRole.Arn
      FoundationModel: !Ref BedrockFoundationModel
      Instruction: |
        You are a helpful AI assistant for the Finance & Travel Knowledge Hub, specializing in financial guidance and travel information.
        
        Your role is to:
        1. Answer questions about personal finance, investing, banking, consumer protection, and travel safety
        2. Use the passage retrieval tool to find relevant information from authoritative sources
        3. Provide accurate, helpful responses based on retrieved passages from trusted government and educational sources
        4. When uncertain, acknowledge limitations and suggest consulting official sources or professionals
        
        Your knowledge base includes content from:
        - Investor.gov: Investment basics, alerts, financial tools, and glossary
        - Consumer Financial Protection Bureau (CFPB): Consumer finance topics and regulations
        - FDIC: Banking protection and consumer resources
        - CDC Travel: Country health information and travel guides
        - State Department: Travel advisories and country information
        - TSA: Travel security and prohibited items
        - FAA: Aviation and traveler information
        - UK Government: Financial services and travel advice
        
        Always:
        - Be helpful, accurate, and professional
        - Cite sources when using retrieved information
        - Focus on educational and informational content
        - Encourage users to verify important financial or travel decisions with official sources
        
        Never:
        - Provide specific financial advice or recommendations
        - Make guarantees about investment returns or travel safety
        - Replace professional financial or medical consultation
      IdleSessionTTLInSeconds: 600
      AutoPrepare: true
      ActionGroups:
        - ActionGroupName: CoveoPassageRetrieval
          Description: 'Retrieve relevant passages from Finance & Travel knowledge base'
          ActionGroupExecutor:
            Lambda: !Ref PassageToolFunctionArn
          FunctionSchema:
            Functions:
              - Name: retrieve_passages
                Description: 'Search for relevant text passages in the finance and travel knowledge base using semantic search'
                Parameters:
                  query:
                    Description: 'The search query or question to find relevant passages for'
                    Type: string
                    Required: true
                  k:
                    Description: 'Number of passages to retrieve (1-20, default 5)'
                    Type: number
                    Required: false
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

  # Lambda permission for Bedrock Agent to invoke passage tool
  PassageToolInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PassageToolFunctionArn
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !GetAtt CoveoAgent.AgentArn

  # Agent Alias (production)
  AgentAlias:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentId: !Ref CoveoAgent
      AgentAliasName: production
      Description: Production alias for Coveo workshop agent

  # Store Agent ID in SSM Parameter Store
  AgentIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${StackPrefix}/coveo/agent-id'
      Description: Bedrock Agent ID
      Type: String
      Value: !Ref CoveoAgent
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

  # Store Agent Alias ID in SSM Parameter Store
  AgentAliasIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${StackPrefix}/coveo/agent-alias-id'
      Description: Bedrock Agent Alias ID
      Type: String
      Value: !GetAtt AgentAlias.AgentAliasId
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

Outputs:
  AgentId:
    Description: Bedrock Agent ID
    Value: !Ref CoveoAgent
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-id'

  AgentArn:
    Description: Bedrock Agent ARN
    Value: !GetAtt CoveoAgent.AgentArn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-arn'

  AgentAliasId:
    Description: Bedrock Agent Alias ID
    Value: !GetAtt AgentAlias.AgentAliasId
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-alias-id'

  AgentAliasArn:
    Description: Bedrock Agent Alias ARN
    Value: !GetAtt AgentAlias.AgentAliasArn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-alias-arn'

  AgentRoleArn:
    Description: Bedrock Agent IAM Role ARN
    Value: !GetAtt BedrockAgentRole.Arn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-role-arn'

  InvokeEndpoint:
    Description: Endpoint for invoking the agent (use AWS SDK)
    Value: !Sub 'https://bedrock-agent-runtime.${AWS::Region}.amazonaws.com'
