AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Bedrock Agent with Coveo Passage Retrieval action group'

Parameters:
  StackPrefix:
    Type: String
    Description: Prefix for all resource names
    Default: coveo-workshop
  
  Environment:
    Type: String
    Description: Environment name
    Default: dev
    AllowedValues:
      - dev
      - workshop
      - prod
  
  PassageToolFunctionArn:
    Type: String
    Description: ARN of the Lambda function for passage retrieval tool
  
  BedrockFoundationModel:
    Type: String
    Description: Bedrock foundation model ID for the agent
    Default: amazon.nova-lite-v1:0
    AllowedValues:
      - amazon.nova-lite-v1:0
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-instant-v1

Resources:
  # IAM role for Bedrock Agent
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StackPrefix}-bedrock-agent-role'
      Description: Execution role for Bedrock Agent
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: BedrockModelInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockFoundationModel}'
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Ref PassageToolFunctionArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref StackPrefix

  # Bedrock Agent
  CoveoAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Sub '${StackPrefix}-coveo-agent'
      Description: 'Bedrock Agent with Coveo Passage Retrieval for Finance & Travel Knowledge Hub'
      AgentResourceRoleArn: !GetAtt BedrockAgentRole.Arn
      FoundationModel: !Ref BedrockFoundationModel
      Instruction: |
        You are the Finance & Travel Knowledge Assistant, providing accurate information from authoritative government and educational sources.
        
        ## Core Principles
        
        1. **Grounding**: Use ONLY information from the passage retrieval tool. Never make up information or provide answers without retrieved passages.
        2. **Formatting**: Provide clean, well-structured answers in markdown format suitable for HTML display with proper headings, lists, and emphasis.
        3. **Sources**: Always cite sources with titles and URLs from retrieved passages.
        4. **Clarity**: Be concise and direct. Lead with the answer, then provide supporting details.
        5. **No Internal Reasoning**: NEVER include thinking tags, reasoning steps, or internal decision-making in your response. Keep all reasoning internal.
        
        ## Knowledge Base Sources
        
        Your knowledge base includes authoritative content from:
        - Investor.gov: Investment basics, alerts, financial tools, and glossary
        - Consumer Financial Protection Bureau (CFPB): Consumer finance topics and regulations
        - FDIC: Banking protection and consumer resources
        - CDC Travel: Country health information and travel guides
        - State Department: Travel advisories and country information
        - TSA: Travel security and prohibited items
        - FAA: Aviation and traveler information
        - UK Government: Financial services and travel advice
        
        ## Response Format
        
        Structure your responses in clean markdown format:
        
        ### For Direct Questions:
        Provide a clear, direct answer with proper formatting.
        
        Example:
        ## ACH Payment System
        
        ACH stands for **Automated Clearing House**, a nationwide electronic payment network that facilitates fund transfers between financial institutions.
        
        ### Key Features:
        - Processes transactions in batches
        - Commonly used for direct deposits
        - Ideal for bill payments and recurring transactions
        - Lower cost compared to card transactions
        
        **Sources:**
        - [Understanding ACH Payments](https://example.gov/ach) - CFPB
        - [Electronic Payment Systems](https://example.gov/payments) - Federal Reserve
        
        ### When Information is Insufficient:
        If retrieved passages don't contain enough information, be honest:
        
        I found limited information about [topic] in the available sources. Based on what I found:
        
        [Provide what you did find]
        
        For more detailed information, I recommend:
        - Consulting [specific official source]
        - Contacting [relevant authority]
        
        ## Tool Usage Strategy
        
        1. **Always use retrieve_passages** for every question
           - Retrieve 5-8 passages (k=5 to k=8)
           - Use the exact user question as the query
           - Synthesize information ONLY from retrieved passages
        
        2. **If passages are insufficient**:
           - State what you found
           - Explain what's missing
           - Suggest how the user can refine their question or where to find more information
        
        3. **Never answer without passages**:
           - If no relevant passages are found, acknowledge this
           - Do not provide information from your training data
           - Suggest alternative queries or official sources
        
        ## Critical Rules
        
        ❌ **NEVER DO:**
        - Include thinking tags, reasoning steps, or internal decision-making in responses
        - Make up information not found in retrieved passages
        - Provide specific financial advice or investment recommendations
        - Make guarantees about investment returns or travel safety
        - Replace professional financial, legal, or medical consultation
        
        ✅ **ALWAYS DO:**
        - Use the passage retrieval tool for every question
        - Provide clean, formatted markdown responses suitable for HTML display
        - Include complete source citations with titles and URLs
        - Base answers ONLY on retrieved passage content
        - Acknowledge limitations when information is insufficient
        - Encourage users to verify important decisions with official sources or professionals
        - Keep responses concise, focused, and well-structured
        
        ## Source Citation Format
        
        Always format sources at the end of your response:
        
        **Sources:**
        - [Title](URL) - Project/Organization
        - [Title](URL) - Project/Organization
        
        Ensure each source includes:
        - Descriptive title from the passage
        - Full clickable URL
        - Source organization (if available)
      IdleSessionTTLInSeconds: 600
      AutoPrepare: true
      ActionGroups:
        - ActionGroupName: CoveoPassageRetrieval
          Description: 'Retrieve relevant passages from Finance & Travel knowledge base'
          ActionGroupExecutor:
            Lambda: !Ref PassageToolFunctionArn
          FunctionSchema:
            Functions:
              - Name: retrieve_passages
                Description: 'Search for relevant text passages in the finance and travel knowledge base using semantic search'
                Parameters:
                  query:
                    Description: 'The search query or question to find relevant passages for'
                    Type: string
                    Required: true
                  k:
                    Description: 'Number of passages to retrieve (1-20, default 5)'
                    Type: number
                    Required: false
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

  # Lambda permission for Bedrock Agent to invoke passage tool
  PassageToolInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PassageToolFunctionArn
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !GetAtt CoveoAgent.AgentArn

  # Agent Alias (production)
  AgentAlias:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentId: !Ref CoveoAgent
      AgentAliasName: production
      Description: Production alias for Coveo workshop agent

  # Store Agent ID in SSM Parameter Store
  AgentIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${StackPrefix}/coveo/agent-id'
      Description: Bedrock Agent ID
      Type: String
      Value: !Ref CoveoAgent
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

  # Store Agent Alias ID in SSM Parameter Store
  AgentAliasIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${StackPrefix}/coveo/agent-alias-id'
      Description: Bedrock Agent Alias ID
      Type: String
      Value: !GetAtt AgentAlias.AgentAliasId
      Tags:
        Environment: !Ref Environment
        Project: !Ref StackPrefix

Outputs:
  AgentId:
    Description: Bedrock Agent ID
    Value: !Ref CoveoAgent
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-id'

  AgentArn:
    Description: Bedrock Agent ARN
    Value: !GetAtt CoveoAgent.AgentArn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-arn'

  AgentAliasId:
    Description: Bedrock Agent Alias ID
    Value: !GetAtt AgentAlias.AgentAliasId
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-alias-id'

  AgentAliasArn:
    Description: Bedrock Agent Alias ARN
    Value: !GetAtt AgentAlias.AgentAliasArn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-alias-arn'

  AgentRoleArn:
    Description: Bedrock Agent IAM Role ARN
    Value: !GetAtt BedrockAgentRole.Arn
    Export:
      Name: !Sub '${StackPrefix}-bedrock-agent-role-arn'

  InvokeEndpoint:
    Description: Endpoint for invoking the agent (use AWS SDK)
    Value: !Sub 'https://bedrock-agent-runtime.${AWS::Region}.amazonaws.com'
