site_name: Coveo + AWS Workshop
site_description: Hands-on workshop demonstrating three progressive AI integration patterns with AWS and Coveo
site_author: Coveo
site_url: https://kpullagu.github.io/aws-coveo-workshop-stackset/

# Repository
repo_name: aws-coveo-workshop-stackset
repo_url: https://github.com/kpullagu/aws-coveo-workshop-stackset

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - mermaid2

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 2

# Navigation
nav:
  - Home: index.md
  
  - Lab 1 - Coveo Discovery:
    - Introduction: lab1/index.md
    - Architecture: lab1/architecture.md
    - Sample Queries: lab1/queries.md
  
  - Lab 2 - Bedrock Agent:
    - Introduction: lab2/index.md
    - Architecture: lab2/architecture.md
  
  - Lab 3 - AgentCore + MCP:
    - Introduction: lab3/index.md
    - Architecture: lab3/architecture.md
  
  - Lab 4 - Chatbot:
    - Introduction: lab4/index.md
    - Memory: lab4/memory.md
    - Use Cases: lab4/use-cases.md
  
  - Resources:
    - Architecture Diagrams: resources/diagrams.md
    - Code References: resources/code.md
    - Additional Reading: resources/reading.md

# Extra CSS and JavaScript
extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/example/aws-coveo-workshop
    - icon: fontawesome/brands/aws
      link: https://aws.amazon.com

# Copyright
copyright: Copyright &copy; 2025 AWS + Coveo
